# Comprehensive configuration sample showcasing grouped settings

core:
  # --- Core polling cadence -----------------------------------------------
  verbose: true                      # Emit verbose logging to stdout
  poll_interval: 10                  # Seconds between GitHub poll cycles

rate_limits:
  # --- Rate limit management ----------------------------------------------
  max_request_rate: 20               # Requests per minute cap enforced by scheduler
  max_hourly_requests: 2000          # Hard hourly ceiling (0 autodetects via API)
  rate_limit_margin: 0.7             # Fraction of hourly budget reserved as safety buffer
  rate_limit_refresh_interval: 45    # Seconds between /rate_limit checks
  retry_rate_limit_endpoint: true    # Continue probing the endpoint after the first failure
  rate_limit_retry_limit: 5          # Maximum scheduled retries when retries are enabled

repository_overrides:
  "octocat/*":
    actions:
      only_poll_prs: true
      delete_stray: false
      hooks_enabled: false
    hooks:
      actions:
        - type: command
          command: scripts/notify.sh
      event_actions:
        pull_request.merged:
          - type: http
            endpoint: https://hooks.example/merged
            method: PUT
            parameters:
              channel: pr-updates

logging:
  # --- Logging -------------------------------------------------------------
  log_level: debug                   # Default log verbosity
  log_compress: true                 # Compress rotated log files on disk
  log_sidecar: true                  # Display log sidecar in the TUI
  request_caddy_window: true         # Show request queue statistics sidecar
  log_categories:
    logging: trace                   # Override log level for specific categories
    history: debug                   # Elevate history logging for audit output

network:
  # --- Network behaviour --------------------------------------------------
  http_timeout: 60                   # HTTP request timeout in seconds
  http_retries: 7                    # Retry attempts for transient HTTP failures
  download_limit: 11                 # Download rate limit (bytes per second)
  upload_limit: 12                   # Upload rate limit (bytes per second)
  max_download: 13                   # Maximum cumulative download in bytes
  max_upload: 14                     # Maximum cumulative upload in bytes
  http_proxy: http://proxy           # Proxy URL for HTTP requests
  https_proxy: http://secureproxy    # Proxy URL for HTTPS requests

ui:
  tui_refresh_interval: 650          # Refresh cadence for the TUI in milliseconds

features:
  # --- Integrations -------------------------------------------------------
  use_graphql: true                  # Prefer GraphQL API for pull request listing

workflow:
  # --- Branch management --------------------------------------------------
  dry_run: true                    # Simulate operations without applying changes
  stray_detection_engine: rule       # Choose rule, heuristic, or both (defaults to rule)
