# Example configuration for autogithubpullmerge
verbose = true
poll_interval = 60
max_request_rate = 100
rate_limit_margin = 0.7
use_graphql = true
log_compress = false
log_sidecar = false

[log_categories]
logging = "debug"
