name: Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format git

      - name: Check formatting
        run: |
          set -e
          files=$(git ls-files | grep -E '\\.(c|cc|cpp|cxx|h|hh|hpp|hxx)$' || true)
          if [ -z "$files" ]; then
            echo "No C/C++ files to check."
            exit 0
          fi
          echo "$files" | xargs -I{} clang-format -n --Werror {}

