name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      VCPKG_FEATURE_FLAGS: manifests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang-tidy g++ git

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true

      - name: Configure (generate compile_commands)
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_CXX_STANDARD=23 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy on src
        run: |
          set -e
          files=$(git ls-files "src/**/*.cpp" | tr '\n' ' ')
          if [ -z "$files" ]; then
            echo "No source files to lint."
            exit 0
          fi
          clang-tidy -p build $files --warnings-as-errors='*'

